export const initialState = {
  isLoading: false,
  error: null,
  campers: [],
  arrayFavoriteCampers: [],
  camperMoreInfo: null,
  pageOfCampers: 1,
  limitItemsOfCampers: 4,
  isButtonLoadMore: true,
  isModallMoreInfo: false,
  idCamperShowMore: null,
  filteredVanType: "",
  filteredEquipment: "",
  location: "",
};
